# Generated by Django 5.2.7 on 2025-10-07 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('horaire_travail', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annonces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Freelance', 'Freelance')], max_length=100)),
                ('dateLimite', models.DateField()),
                ('datePublication', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offre_emplois.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Candidatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCandidature', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée')], default='En attente', max_length=100)),
                ('emailsent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annonces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offre_emplois.annonces')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offre_emplois.people')),
            ],
        ),
    ]
