# Generated by Django 5.2.7 on 2025-10-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offre_emplois', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='annonces',
            table='annonces',
        ),
        migrations.AlterModelTable(
            name='candidatures',
            table='candidatures',
        ),
        migrations.AlterModelTable(
            name='companies',
            table='companies',
        ),
        migrations.AlterModelTable(
            name='people',
            table='people',
        ),
    ]
