# Generated by Django 5.2.7 on 2025-10-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offre_emplois', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='people',
            name='user',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
