# Generated by Django 5.2.7 on 2025-10-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre_emplois', '0002_remove_companies_user_remove_people_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
        migrations.AddField(
            model_name='people',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
        migrations.AlterField(
            model_name='people',
            name='cv',
            field=models.FileField(upload_to='cvs/'),
        ),
        migrations.AlterModelTable(
            name='companies',
            table=None,
        ),
    ]
