# Generated by Django 5.2.7 on 2025-10-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre_emplois', '0002_alter_annonces_table_alter_candidatures_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
