# Generated by Django 5.2.7 on 2025-10-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offre_emplois', '0003_companies_password_people_password_alter_people_cv_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companies',
            table='companies',
        ),
    ]
