# Generated by Django 5.2.7 on 2025-10-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offre_emplois', '0004_alter_companies_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companies',
            table=None,
        ),
    ]
