# Generated by Django 5.2.7 on 2025-10-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offre_emplois', '0006_user_alter_annonces_companies_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
