# Generated by Django 5.2.7 on 2025-10-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offre_emplois', '0007_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
