# Generated by Django 5.2.7 on 2025-10-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offre_emplois', '0008_remove_user_created_at_remove_user_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
