# Generated by Django 5.2.7 on 2025-10-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre_emplois', '0009_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='horaire_travail',
        ),
        migrations.AddField(
            model_name='annonces',
            name='horaire_travail',
            field=models.CharField(default='Temps plein', max_length=100),
        ),
    ]
