# Generated by Django 5.2.7 on 2025-10-16 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre_emplois', '0010_remove_people_horaire_travail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('departement', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='annonces',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='candidatures',
            name='annonces',
        ),
        migrations.RemoveField(
            model_name='candidatures',
            name='people',
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_emploi', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('departement', models.CharField(max_length=100)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_contrat', models.CharField(max_length=50)),
                ('horaires', models.CharField(max_length=100)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offre_emplois.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offre_emplois.annonce')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offre_emplois.personne')),
            ],
        ),
        migrations.DeleteModel(
            name='Companies',
        ),
        migrations.DeleteModel(
            name='Annonces',
        ),
        migrations.DeleteModel(
            name='Candidatures',
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
