# Generated by Django 5.2.7 on 2025-10-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre_emplois', '0011_entreprise_personne_remove_annonces_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
